### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#1]
In this exciting task, we invite contributors to bring the vision to life by implementing the frontend for SponsoHive's home page. The groundwork has been laid out in a video, and now we need your expertise to translate that design into a fully functional and visually stunning reality.

Design to Life:
Your primary mission is to transform the intricate details of the design into a dynamic and captivating frontend for SponsoHive's home page.

Link:https://res.cloudinary.com/dtnfycvwp/video/upload/v1734201681/Vite_React_TS_-_Google_Chrome_2024-12-14_23-58-09_mirxrg.mp4
Background-image-Link:https://res.cloudinary.com/dtnfycvwp/image/upload/v1734284613/cardBG_ytl7di.jpg

Leverage the power of Material UI, Ant Design, and Tailwind CSS, all pre-installed and ready for your creative touch.
Submit a pull request with your completed frontend, and let's make the home page an enchanting gateway to the collaborative world of Hitch.

Time: 48 hours.
 
Please comment to claim the issue.

**Comment by Ada-kr** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by bikram993298** [comment]
Will u assign it,I have done all things

**Comment by bikram993298** [comment]
My pr has been merged but I have not got points

**Comment by ANJALIJAISWAL4213** [comment]
@bikram993298 this issue was assigned to snehal so your pull request can't be accepted

**Comment by ANJALIJAISWAL4213** [comment]
@Snehalgupta-07 do continue working on this issue

**Comment by ANJALIJAISWAL4213** [comment]
@Snehalgupta-07 share you discord username with me

**Comment by Snehalgupta-07** [comment]
> @Snehalgupta-07 share you discord username with me

snehal_67423
