### ISSUE TITLE
Design Login/Signup Button

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#2]
In this exciting task, we invite contributors to bring the vision to life by using their creative thinking and design for SponsoHive's Login/Signup Button.. The groundwork has been laid out in a video, and now we need your expertise to translate a design that suits the website into a fully functional and visually stunning reality.
It simply means you have to use your creativity to design a Login/Signup Button.

Design to Life:
Your primary mission is to transform the intricate details of the Login/Signup Button design into a dynamic and captivating frontend for SponsoHive's home page.

Link:https://res.cloudinary.com/dtnfycvwp/video/upload/v1734201681/Vite_React_TS_-_Google_Chrome_2024-12-14_23-58-09_mirxrg.mp4

Leverage the power of Material UI, Ant Design, and Tailwind CSS, all pre-installed and ready for your creative touch.
Submit a pull request with your completed frontend, and let's make the home page an enchanting gateway to the collaborative world of SponsoHive.

Time: 72 hours.

No Need to Claim the issue, The Best will get merged in 72 hours, Other may get partial points though.

**Comment by Snehalgupta-07** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
please comment on git as claim

**Comment by ANJALIJAISWAL4213** [comment]
For any doubts please contact on discord no other means of contact will be entertained.
