### ISSUE TITLE
Performance Analytics Page Looks Like It Missed the Memo

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#24]
The Performance Analytics page in SponsoHive seems to have wandered off the hive! 🐝 While the rest of our site buzzes with cohesive design and style, this page feels like it belongs to another platform. Let’s bring it back to the hive and align it with the rest of our buzzing, modern aesthetic!

I have put the home page design for reference Link: https://res.cloudinary.com/dtnfycvwp/video/upload/v1734201681/Vite_React_TS_-_Google_Chrome_2024-12-14_23-58-09_mirxrg.mp4

Currently We have our Email aotumation page ready you can use it for reference Link:https://private-user-images.githubusercontent.com/181252396/396097851-62af7f84-b392-4fcb-a426-6b7298db53bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTA4NTIsIm5iZiI6MTczNDQ1MDU1MiwicGF0aCI6Ii8xODEyNTIzOTYvMzk2MDk3ODUxLTYyYWY3Zjg0LWIzOTItNGZjYi1hNDI2LTZiNzI5OGRiNTNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTQ5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGU3Y2EzY2M1ODg5NGNiYmQ0NGMwMmNjOWQzNjU3ODhmNTZjMzIzMzZiMDcxYTEwNzY5OGQ3NGQ5MzgxNDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4xJpJJ28sUb9H2ZPkfCBTm6Wwz9GXZjPBod6LsDxE18

Expected Outcome
The Performance Analytics page should feel like it belongs—seamlessly blending with the rest of the website while maintaining its functionality.

Estimated Time 48 hours

Please claim this issue

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by oopshwet** [comment]
Claim

**Comment by Vardaan-02** [comment]
late again

**Comment by PriyamJChakrabarty** [comment]
: (

**Comment by PriyamJChakrabarty** [comment]
@ANJALIJAISWAL4213  Please update the points!
