### ISSUE TITLE
Breaking the Navbar Free: Time to Componentize!

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#26]
The navbar on SponsoHive's homepage is feeling a little too tied down! 🖼️ Right now, it’s baked directly into the page, but it’s time to give it wings by turning it into a reusable component.

Proposed Action:

Extract the current navbar from the homepage.
Create a standalone Navbar component.
Integrate the new component into the homepage and ensure it's styled and functional.

Outcome:

A sleek, reusable Navbar component that will pave the way for a more modular and maintainable SponsoHive! 🚀 Let’s get this hive buzzing with clean, reusable code!

Estimated Time:24 hours.

Claim this issue.

**Comment by PriyamJChakrabarty** [comment]
Claim
