### ISSUE TITLE
Footer Glow-Up: From Static to Stunning Component!

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#27]
SponsoHive's footer is ready for a transformation! 🌟 Right now, it’s glued to the homepage, but let’s elevate it by turning it into a reusable component and giving it a design upgrade.

A beautifully designed footer creates a lasting impression and reinforces our brand identity.

Proposed Actions:

Extract the current footer and create a standalone Footer component.
Redesign the footer to make it visually appealing and user-friendly:
Add modern layouts and typography.
Use soft gradients or subtle animations to enhance its style.
Consider adding quick links, social media icons, and contact details.

Outcome:

A reusable and visually stunning Footer component that ties the SponsoHive website together beautifully and leaves a lasting impression on users. Let’s make it shine! ✨

Estimated Time:48 hours

Claim this issue

**Comment by kalim-Asim** [comment]
Claim

**Comment by ANJALIJAISWAL4213** [comment]
@kalim-Asim tell me if you are workinh on this issue

**Comment by kalim-Asim** [comment]
Check discord msg

**Comment by kalim-Asim** [comment]
And yes I'm working

**Comment by kalim-Asim** [comment]
@ANJALIJAISWAL4213 pls check my discord msg and tell if I should open pr now or not
