### ISSUE TITLE
Create a Login Page

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#3]
Contributors are invited to realize the goal by developing the frontend for the Login page of SponsoHive in this fascinating work. We need your skills to turn that design into a completely functional and aesthetically pleasing reality after the foundation has been established in a film.

Design to Life: Your main task is to turn the complex design elements into an engaging and dynamic frontend for the SponsoHive login page.

The video can be found at https://res.cloudinary.com/dtnfycvwp/video/upload/v1734284140/Vite_React_TS_-_Google_Chrome_2024-12-15_23-03-02_kctai5.mp4

svg Link:https://res.cloudinary.com/dtnfycvwp/image/upload/v1734285028/authentication_hzot1f.svg

Make use of Material UI, Ant Design, and Tailwind CSS, which are all ready for your creative input and come pre-installed.
Let's turn the home page into an enchanted entryway to the SponsoHive collaborative universe by submitting a pull request with your finished frontend.

Time: 72 hours.

Please comment to claim the issue.

**Comment by Snehalgupta-07** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by rajdeep13-coder** [comment]
I have made a simple Login page with a similar UI as of your website
Any suggestions on improving this is welcome
![Screenshot 2024-12-16 124816](https://github.com/user-attachments/assets/8b4f6d4d-ab3b-4369-9b98-37784550bff4)

Kindly assign this issue to me 
thank you

**Comment by ANJALIJAISWAL4213** [comment]
@rajdeep13-coder please wait this issue has been assigned to someone else and you have to make the exsct login page as specified

**Comment by ANJALIJAISWAL4213** [comment]
For any doubts please contact on discord no other means of contact will be entertained.
