### ISSUE TITLE
Responsive Navbar with Integrated Logo

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#31]
Design a sleek, responsive navbar tailored for SponsoHive, incorporating its logo for a professional and cohesive brand identity. This modern navbar adapts seamlessly to various screen sizes, ensuring optimal user experience across devices. It features clear navigation links, a prominent logo placement, and a collapsible menu for smaller screens. With a clean, visually appealing design, the navbar enhances usability and reinforces the platform's branding.

Points to be noted:
Navbar has to be Responsive
Design has to be elegant
Add logo , it's link is in Logo.txt file
Replace "Sponsorship Platform" with "SponsoHive"
Remove "Analytics and Campaigns" from navbar it should only have home and a creative user  Icon

Estimated Time:48 hours

Note:I will increase the points if work is good

**Comment by kalim-Asim** [comment]
i have a doubt regarding - "Remove "Analytics and Campaigns" from navbar it should only have home and a creative user Icon", then where do i have to place them ?  analytics and campaign route can only be accessed from navbar buttons...

**Comment by kalim-Asim** [comment]
also the logo would look like this...
![Screenshot 2024-12-19 165047](https://github.com/user-attachments/assets/a0d2cdc1-f9ca-40ba-8415-84f8beb11652)
