### ISSUE TITLE
Revamping Core Features Cards

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#32]
The current core features cards on our platform lack visual appeal and do not effectively showcase the platform's key functionalities. We aim to redesign these cards to make them more engaging, visually striking, and user-friendly. The new design should align with the platform's branding, using modern aesthetics and interactive elements to enhance readability and draw attention to the core features. Let's create cards that not only inform but also impress, leaving a lasting impact on our users.

Estimated Time:48 hours

This issue can be claimed 

Please contact on discord in case of doubts no other means like whatsApp will be entertained.

**Comment by official-ashutosh** [comment]
Claim

**Comment by official-ashutosh** [comment]
Creating pr by 5pm

**Comment by official-ashutosh** [comment]
I have unassigned myself from this; you can assign it to someone else.

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by ANJALIJAISWAL4213** [comment]
@Snehalgupta-07 update

**Comment by Snehalgupta-07** [comment]
> @Snehalgupta-07 update

Will raise  pr by tomorrow

**Comment by ANJALIJAISWAL4213** [comment]
@Snehalgupta-07 you deadline has exceeded so update me soon please

**Comment by Snehalgupta-07** [comment]
> @Snehalgupta-07 you deadline has exceeded so update me soon please

I am not able to think of a good card design, u can assign this task to someone else

**Comment by official-ashutosh** [comment]
claim
