### ISSUE TITLE
Enhance Email Automation: Add Time Selection & Non-Responder Dashboard

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#33]
Description:
This issue focuses on enhancing the email automation feature by implementing two key improvements:

Add Time Selection to Email Scheduling:
Extend the existing email scheduling functionality to include time selection, allowing users to specify when emails should be dispatched (e.g., at 10:00 AM).

Implement Non-Responder Tracking with Status Dashboard:
Create a dashboard to display email campaign statistics, including sent, opened, and clicked emails, as well as non-responders. Use dummy data to simulate tracking since backend integration is not yet available.

Expected Outcome:
Email Scheduling: Users can schedule emails at a specific date and time for better engagement.
Dashboard: A simulated real-world status dashboard showcasing campaign insights and non-responder tracking.
Tech Stack:
UI Components: React, Ant Design.
Data Handling: Dummy data in utils/dummyEmailData.js.
Styling: TailwindCSS and Ant Design.

Suggestions for Contributors:
Ensure the time picker integrates smoothly with the existing date range picker.
Make the dashboard visually appealing and easy to understand, as it showcases critical campaign metrics.
Use comments in the dummy data file to clarify its purpose as a temporary frontend simulation.
Feel free to ask questions or suggest additional improvements for these features! 🚀

Estimated Timne:48 hours

This issue can be claimed .

Please contact on discord in case of doubts no other means like whatsApp will be entertained.

**Comment by official-ashutosh** [comment]
claim
