### ISSUE TITLE
🎉 Implement Sign-Up and Sign-In Flow with Mock Local Storage

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#35]
Description:
Create a Sign-Up and Sign-In functionality that allows users to either sign in with their credentials or sign up if they are new. This should simulate user authentication purely on the frontend using localStorage.

Success Criteria:
✅ Sign-Up Page:
Adds a new user to localStorage if credentials are new.
Redirects the user to Home Page upon successful sign-up.

✅ Sign-In Page:
Authenticates user credentials from localStorage.
Redirects the user to Home Page upon successful authentication.

✅ Proper error handling for invalid login attempts or repeated sign-ups.

✅ Both Sign-In and Sign-Up integrate seamless navigation and mock authentication

Estimated Time:36 hours.

This issue can be claimed 

Please contact on discord in case of doubts no other means like whatsApp will be entertained.

**Comment by kalim-Asim** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by kyanmahajan** [comment]
claim
