### ISSUE TITLE
Add Images on Home Page

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#4]
We are inviting participants in this fascinating endeavor to add photographs to the SponsoHive home page in order to make it come to life. We need your skills to turn that design into a completely functional and aesthetically pleasing reality after the foundation has been established in a film.

Design to Life: Your main task is to turn the design's fine elements into an engaging and dynamic frontend for SponsoHive's main page.

https://res.cloudinary.com/dtnfycvwp/image/upload/v1734284417/main_image_lm4f8v.jpg is the link.

Make use of Material UI, Ant Design, and Tailwind CSS, which are all ready for your creative input and come pre-installed.
Let's turn the home page into an enchanted entryway to the SponsoHive collaborative universe by submitting a pull request with your finished frontend.

Time: 48 hours.

Please comment to claim the issue.

**Comment by official-ashutosh** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
For any doubts please contact on discord no other means of contact will be entertained.
