### ISSUE TITLE
Create a SignUp Page

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#5]
Contributors are invited to make thier own design for the SignUp page of SponsoHive by taking reference of login page . We need your skills to turn your creativity into a completely functional and aesthetically pleasing reality after the foundation has been established in a film.

Design for reference: Your main task is to turn the complex design elements into an engaging and dynamic frontend for the SponsoHive SignUp page.

The video can be found at 
https://res.cloudinary.com/dtnfycvwp/upload/v1734284140/Vite_React_TS_-_Google_Chrome_2024-12-15_23-03-02_kctai5.mp4.

svg Link:https://res.cloudinary.com/dtnfycvwp/image/upload/v1734285028/authentication_hzot1f.svg

Make use of Material UI, Ant Design, and Tailwind CSS, which are all ready for your creative input and come pre-installed.
Let's turn the signup page into an enchanted entryway to the SponsoHive collaborative universe by submitting a pull request with your finished frontend.

Time: 48 hours.

Please comment to claim the issue.

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
For any doubts please contact on discord no other means of contact will be entertained.
