### ISSUE TITLE
Frontend Enhancements for Analytics Page with Dummy Data

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#50]
Description
Enhance the frontend of the analytics page by improving data realism, visualization, and interactivity while using dummy data in the absence of a backend. These updates aim to provide a more engaging, intuitive, and realistic user experience.

Tasks
Data Enhancements

Add realistic dummy data for multiple campaigns.
Include time-series data for trend visualization (e.g., daily engagement metrics).
Visualization Improvements

Add a line chart to represent engagement trends over time.
Add a stacked bar chart for better comparison across campaigns or metrics.
Enable interactive hover effects with tooltips.
Campaign Comparison

Create a dropdown or tabs for comparing analytics between campaigns.
Highlight top-performing metrics for visibility.
UI/UX Enhancements

Add loading states and animations for better feedback.
Implement a dark mode toggle.
Fine-tune responsive design for seamless experience across devices.
Interactive Filters

Add filters for metrics based on date range, campaign, or metric type.
Add an "Export as CSV" button to download analytics data for testing.
Annotations on Charts

Highlight key points, such as spikes or drops, using annotations or labels.
Real-Time Simulation

Simulate real-time data updates with a timer to mimic backend analytics.
Acceptance Criteria
 Dummy data includes multiple campaigns with varied metrics.
 Charts display time-series trends and comparative metrics effectively.
 Campaigns can be compared interactively.
 UI is intuitive, responsive, and includes dark mode support.
 Filters and export functionality are implemented.
 Real-time data updates are functional.
Let me know if you want any additional details or modifications! 😊

Estimated Time:48 hours

**Comment by official-ashutosh** [comment]
Claim
