### ISSUE TITLE
Codebase Cleanup and Optimization

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#62]
The repository has accumulated some inconsistencies, duplicate code, and overlapping functionality over time. To maintain quality and ensure the project is easy to navigate for current and future contributors, the following tasks need to be addressed:

Tasks:
Remove Duplicate Code:

Identify and eliminate duplicate state variables, methods, and component definitions.
Consolidate repeated UI elements like buttons, tables, and modal definitions.
Improve File Organization:

Ensure files are logically structured.
Group related components and utilities for better accessibility.
Fix Syntax Issues:

Address any ESLint or Prettier warnings.
Validate React hooks and state management are used correctly.
Update Styling:

Standardize styles across components for a consistent look and feel.
Remove redundant classes or styles.
Test Functionality:

Verify that cleaned-up components (e.g., Campaign Automation) are fully functional and free of runtime errors.
Documentation:

Add comments where necessary for better understanding of complex logic.
Update README or other contributing guides to reflect any changes made during cleanup.
Expected Outcome:
A clean, efficient, and well-documented codebase that is easier for contributors to understand and build upon.
Standardized structure and reduced redundancy in the project files.

Estimated Time:48 hours

**Comment by kalim-Asim** [comment]
Claim
