### ISSUE TITLE
Design Contact Management Dashboard for Email Lists

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#63]
Description:This has to be done in Core Feature one
Develop a dashboard where users can view, filter, and manage their uploaded email lists more effectively.

Key Tasks:

Display all uploaded email lists in a paginated, searchable table.
Include options to view individual lists, sort contacts by attributes (e.g., name, email, category), and export lists.
Integrate categorization and tagging directly into the dashboard.
Implement a bulk-delete option for contacts or lists.
Complexity Additions:

Add data visualization to provide insights into the uploaded lists (e.g., distribution by category, industry, or priority).
Enable collaborative features, such as assigning contacts to different team members with role-based access.

Estimated Time:48 hours

**Comment by ayush-patel1** [comment]
claim
