### ISSUE TITLE
Revamping Core Features Cards

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#66]
The current core features cards on our platform lack visual appeal and do not effectively showcase the platform's key functionalities. We aim to redesign these cards to make them more engaging, visually striking, and user-friendly. The new design should align with the platform's branding, using modern aesthetics and interactive elements to enhance readability and draw attention to the core features. Let's create cards that not only inform but also impress, leaving a lasting impact on our users.

Estimated Time:48 hours

This issue can be claimed

Please contact on discord in case of doubts no other means like whatsApp will be entertained.

**Comment by official-ashutosh** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
@official-ashutosh i had assigned this issue at first to you only so this time I want you to update me on this after 24 hours

**Comment by official-ashutosh** [comment]
@ANJALIJAISWAL4213 please check discord
