### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#7]
Adding images to core features

Here we want your creativity to thrive .
So you basically need to search for images that suits the website requirements for all 8 core features.

Website Link for reference:
Link:https://res.cloudinary.com/dtnfycvwp/video/upload/v1734201681/Vite_React_TS_-_Google_Chrome_2024-12-14_23-58-09_mirxrg.mp4

Time: 48 hours.

Please comment to claim the issue.

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
For any doubts please contact on discord no other means of contact like whatsapp will be entertained.
