### ISSUE TITLE
Design and Implement Dynamic Opt-Out Management System

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Frontend#76]
New Page: Compliance
This page is dedicated to ensuring that all email campaigns sent through SponsoHive adhere to GDPR and CAN-SPAM regulations. It serves as a centralized hub for users to manage consent, opt-out requests, sender verification, and legal compliance for international campaigns. Each feature ensures transparency, accountability, and ease of regulatory adherence.

Description:
A Dynamic Opt-Out Management System needs to be integrated into a new Compliance page, ensuring GDPR and CAN-SPAM compliance for all email campaigns. The system should:

Detect and process opt-out requests automatically from email recipients via a dedicated endpoint.
Maintain and display a Suppression List on the Compliance page, listing all opted-out email addresses per campaign.
Include an Audit Trail that logs each opt-out request with details such as the timestamp, campaign ID, and reason for opting out (if provided).
Allow users to export opt-out data for compliance reporting.
Complexity:

Building real-time synchronization between email campaign data and suppression lists.
Developing a secure, scalable backend to store and retrieve opt-out data.
Implementing a user-friendly interface for suppression list management and audit logs.
Handling a high volume of opt-out requests efficiently, even during peak campaigns.

Estimated Time:48 hours

**Comment by official-ashutosh** [comment]
Claim
