### ISSUE TITLE
Create Email Automation Page

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SponsoHive-Frontend#9]
Contributors are invited to make their own design for the Email Automation page of SponsoHive. show your creativity and create a simple yet elegant design which includes the below mentioned features:

Features required-Create custom email templates. Schedule automated email dispatch and set follow-up sequences for non-responders.

The design of the buttons should be consistent with that of the home page.

Link : https://res.cloudinary.com/dtnfycvwp/video/upload/v1734201681/Vite_React_TS_-_Google_Chrome_2024-12-14_23-58-09_mirxrg.mp4

Make use of Material UI, Ant Design, and Tailwind CSS, which are all ready for your creative input and come pre-installed.
Let's turn the performance page into an enchanted entryway to the SponsoHive collaborative universe by submitting a pull request with your finished frontend.

Note- Kindly ensure that your page is responsive for different devices.

Time: 48 hours.

Please comment to claim the issue.

**Comment by official-ashutosh** [comment]
claim

**Comment by dark-dev2475** [comment]
in the pages folder there is no Email automation page specified shall i make a new page for the same or I shall make it in campaign automation file

**Comment by PrinkalDhingra** [comment]
Make it in campaign automation file only
